version: "3"

services:
  basket-service:
    build: basket-service/
    ports: 
     - "8000:8000"
    environment:
      - "BFF_URL=http://bff:4000"

  basket-utils:
    build: basket-utils/
    volumes:
      - "./basketData/games:/app/games"

  bff:
    build: bff/
    ports: 
      - "4000:4000"
    environment:
      - "BASKET_URL=http://basket-service:8000"

  
  ipad-controller:
    build: ipad-controller/
    ports: 
      - "3001:80"
  
  ui: 
    build: ui/
    ports: 
      - "3000:80"